### ISSUE TITLE
integrate raindex with defillama

### ISSUE THREAD

**Issue by dcatki** [rainlanguage/rain.orderbook#919]
https://docs.llama.fi/list-your-project/submit-a-project

**Comment by rouzwelt** [comment]
for TVL: 
- we need list of orderbook contracts on every chain we have deployments, then we can get all the current tokens addresses that an orderbook holds by a sg query, and with defillama helpers we can get each token's balance

project metadata: 
- we need icon 240 x 240

for VOL:
- same as TVL, however for ease of implementation, we probably need to add some new entity on out sg that can calculate total vol for a token, since defillama doesn allow to add new custom npm dependency, it just allows for onchain calls and some helper fns that it already provides through its API

**Comment by rouzwelt** [comment]
integrated
